### PR TITLE
Vendor the ATF m4 files from freebsd/atf@atf-0.22

### PR DESCRIPTION
**Pull request by ngie-eign**
This is being done so the ATF project can move to another build system,
like cmake, without having to completely rework the build processes from
Kyua down--which would be a more painful operation to perform.

Requires: #27

### CODE REVIEW

**Review by emaste — COMMENTED** [review]
Instead of "Submitted by" you can just set the git author

**Comment by emaste** [comment]
Overall looks fine

**Comment by ngie-eign** [comment]
> Instead of "Submitted by" you can just set the git author

Hmm? Are you perhaps thinking of another PR?

**Comment by ngie-eign** [comment]
> > Instead of "Submitted by" you can just set the git author
> 
> Hmm? Are you perhaps thinking of another PR?

No, you weren’t.. yeah, I should have cherry-picked the original commit and amended it instead of doing that 😮‍💨.

**Pull request merged**
