### PR TITLE
Apply Markdown to NEWS, INSTALL, and README

### PR DESCRIPTION
**Pull request by fel1x-developer**
COPYING is moved to LICENSE
README, INSTALL, and NEWS are moved to README.md, INSTALL.md, and NEWS.md, respectively.

Markdown is applied to those three files like kyua repo.

### CODE REVIEW

**Review by ngie-eign — CHANGES_REQUESTED** [review]
The rationale for these changes aren't clarified in the commit message(s). Please describe why, for instance, COPYING was moved to LICENSE.

**Comment by fel1x-developer** [comment]
Sorry. Moving COPYING to LICENSE was my mistake.

**Comment by ngie-eign** [comment]
Could you please rebase on master?

**Review by ngie-eign — APPROVED** [review]

**Comment by ngie-eign** [comment]
Sorry for the earlier confusing request. I accidentally mistook this repo for one of the others you're working on.

**Pull request merged**
